var express = require("express")
var resController = require("./controllers/restaurantController")
var reviewController = require("./controllers/reviewController")
var userController = require("./controllers/userController")
var app = express()

app.use(express.static("./public"))
app.use(express.json())

app.route("/getRestaurants").get(resController.getAllRestaurants)
app.route("/getResInfo/:id").get(resController.getResInfo)
app.route("/getResImages/:id").get(resController.getResImages)
app.route("/addRestaurants").post(resController.postRestaurant)
app.route("/uploadImages").post(resController.storeImage)
app.route("/getResReviews/:id").get(reviewController.getResReviews)
app.route("/addReviews").post(reviewController.postReview)
app.route("/editReviews/:id").put(reviewController.editReview)
app.route("/deleteReviews/:id").delete(reviewController.deleteReview)
app.route("/getAllLikes").get(reviewController.getAllLikes)
app.route("/likeReview").post(reviewController.likeReview)
app.route("/removeLike").delete(reviewController.removeLike)
app.route("/getAllUsers").get(userController.getAllUsers)
app.route("/getUserInfo/:id").get(userController.getUserInfo)
app.route("/login").post(userController.login)
app.route("/addUsers").post(userController.postUser)
app.route("/editProfile/:id").post(userController.editUser)
app.route("/getResetLink").post(userController.getResetLink)
app.route("/resetPassword/:id").put(userController.resetPassword)
app.route("/deleteUser/:id").delete(userController.deleteUser)

app.listen(8080, "127.0.0.1")
console.log("web server running @ http://127.0.0.1:8080")